version: '3.8'

services:
  prestashop:
    image: prestashop/prestashop:8.1.3
    platform: linux/amd64
    container_name: prestashop-pmna
    ports:
      - "8080:80"
    volumes:
      - ./prestashop:/var/www/html
      - ./custom-modules:/var/www/html/modules/custom-modules
      - ./themes:/var/www/html/themes/custom-themes
      - ./overrides:/var/www/html/override
    environment:
      - DB_SERVER=${DB_SERVER}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db

  db:
    image: mysql:5.7
    platform: linux/amd64
    container_name: prestashop-db-pmna
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_HOST=% 
    volumes:
      - prestashop-db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=db
    depends_on:
      - db

volumes:
  prestashop-db-data:
