version: '3.8'

services:
  prestashop:
    image: prestashop/prestashop:8.1.3
    platform: linux/amd64  # Forces the x86_64 architecture
    container_name: prestashop
    ports:
      - "8080:80"
    volumes:
      - ./prestashop:/var/www/html
      - ./custom-modules:/var/www/html/modules/custom-modules  # Custom modules
      - ./themes:/var/www/html/themes/custom-themes            # Custom themes
      - ./overrides:/var/www/html/override                     # Overrides
    environment:
      - PS_DEV_MODE=1
      - DB_SERVER=db
      - DB_NAME=prestashop
      - DB_USER=root
      - DB_PASSWORD=root
    depends_on:
      - db

  db:
    image: mysql:5.7
    platform: linux/amd64  # Forces the x86_64 architecture
    container_name: prestashop-db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=prestashop
    volumes:
      - prestashop-db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=db  # Connect to MySQL service
    depends_on:
      - db

volumes:
  prestashop-db-data:
